Intake and containment statemachines
thedropbears/pypowerup pull request #12
Opened 2018-02-12 09:44 UTC by Matthew13479

2018-02-13 04:18 UTC, auscompgeek commented on pyswervedrive/swervechassis.py
> +            if self.momentum and abs(self.imu.getHeadingRate()) < 0.0001:
This hack should not be in your code…

2018-02-13 04:50 UTC, auscompgeek requested changes

2018-02-13 04:50 UTC, auscompgeek commented on components/intake.py
>          """Returns True of the current output of the motor is above 3"""
Please fix your documentation.

2018-02-14 07:39 UTC, auscompgeek commented on components/intake.py
>          """Gets the distance of the infrared sensor in mm"""
I think this documented behaviour is wrong.

2018-02-14 08:28 UTC, auscompgeek commented on robot.py
> +        self.sd = NetworkTables.getTable("SmartDashboard")
…

2018-02-14 08:28 UTC, auscompgeek commented on robot.py
> +        self.lift_motor = ctre.WPI_TalonSRX(0)
????????

2018-02-14 08:54 UTC, fizzlebert approved these changes

2018-02-14 08:57 UTC, merged