Clean up NetworkTables usage
thedropbears/pypowerup pull request #18
Opened 2018-02-17 06:23 UTC by auscompgeek

2018-02-21 07:25 UTC, auscompgeek commented
@ArthurAllshire seeing as you merged this into your branch, did you want to actually review this? :P

2018-02-22 00:24 UTC, ArthurAllshire requested changes
IDK how we do this - I don't think we can merge this PR without breaking mine. I think to make changes you should just push to my auto branch...

2018-02-22 00:24 UTC, ArthurAllshire commented on components/lifter.py
> +    @magicbot.feedback
Will turning this into a magic bot feedback not mean it is called every iteration, thus reading the sensor position every iteration, slowing down the code as it reads over the CAN bus?

2018-02-22 00:24 UTC, ArthurAllshire commented on components/lifter.py
> +    @magicbot.feedback
Ditto my above comment.

2018-02-22 00:26 UTC, auscompgeek commented
This is already merged in your PR.

2018-02-22 00:26 UTC, auscompgeek commented on components/lifter.py
> +    @magicbot.feedback
Yes. Yes it does.

2018-03-05 09:46 UTC, merged