Intake state machine changes
thedropbears/pypowerup pull request #2
Opened 2018-02-07 08:21 UTC by Matthew13479

2018-02-07 12:53 UTC, auscompgeek requested changes

2018-02-07 12:53 UTC, auscompgeek commented on components/intake.py
> +        self.intake_right.set(self.intake_right.ControlMode.Follower, 2)
What on earth is going on here. Even the tests don't know what ID 2 is.

Use [TalonSRX.follow()](https://robotpy.readthedocs.io/projects/ctre/en/latest/api_talonsrx.html#ctre.talonsrx.TalonSRX.follow), and pass in an actual TalonSRX object.

2018-02-07 12:53 UTC, auscompgeek commented on components/intake.py
> +    joystick: wpilib.Joystick
nonononononononononononononononononononononononononononononono

2018-02-07 12:53 UTC, auscompgeek commented on components/intake.py
>          self.cube_distance = max(min(distance, 35.0), 4.5)
So, uh, can we please stop reinventing the wheel here? The RobotPy common driver library exists for a reason.

2018-02-07 12:53 UTC, auscompgeek commented on components/intake.py
>      def intake_rotate(self, value):
Why is this method name not a verb?

2018-02-09 07:44 UTC, auscompgeek submitted a review, later dismissed

2018-02-09 07:44 UTC, auscompgeek commented on components/intake.py
> +    def rotate_intake(self, value):
Don't I already know that I'm going to rotate the intake if I ask the intake to rotate?

2018-02-09 07:44 UTC, auscompgeek commented on components/intake.py
> +        self.cube_distance * 10
what.

2018-02-09 07:44 UTC, auscompgeek commented on components/intake.py
>          pass
Why is execute empty?

2018-02-11 03:10 UTC, ArthurAllshire approved these changes

2018-02-11 03:11 UTC, merged